apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: correlator
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/projectriff/correlator
